# Generated by Django 4.2.14 on 2024-07-18 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
